"""Shared scanning backend for CLI and GUI."""

from .cache import CACHE_DB
from .env import (
    BASE_DIR,
    THEME_AUTO,
    THEME_DARK,
    THEME_LIGHT,
    UPLOAD_AUTO,
    UPLOAD_MANUAL,
    UPLOAD_NEVER,
    get_api_key,
    is_valid_api_key,
    get_requests_per_minute,
    get_theme_mode,
    get_upload_timeout_minutes,
    get_upload_mode,
    get_workers,
    remove_api_key_from_env,
    save_api_key_to_env,
    save_requests_per_minute_to_env,
    save_theme_mode_to_env,
    save_upload_timeout_minutes_to_env,
    save_upload_mode_to_env,
    save_workers_to_env,
)
from .defaults import DEFAULT_REQUESTS_PER_MINUTE, DEFAULT_SCAN_WORKERS, DEFAULT_UPLOAD_TIMEOUT_MINUTES
from .models import ResultStatus, ScannerConfig, ScanResult, ScanTarget, ScanTargetKind, ThreatLevel, UploadTarget
from .reporting import build_summary, write_report
from .service_results import format_hash, is_valid_hash
from .service import ScannerService

__all__ = [
    "BASE_DIR",
    "CACHE_DB",
    "ResultStatus",
    "ScannerConfig",
    "ScannerService",
    "ScanResult",
    "ScanTarget",
    "ScanTargetKind",
    "ThreatLevel",
    "UploadTarget",
    "build_summary",
    "write_report",
    "format_hash",
    "is_valid_hash",
    "get_api_key",
    "is_valid_api_key",
    "save_api_key_to_env",
    "remove_api_key_from_env",
    "get_requests_per_minute",
    "save_requests_per_minute_to_env",
    "get_workers",
    "save_workers_to_env",
    "get_upload_timeout_minutes",
    "save_upload_timeout_minutes_to_env",
    "get_theme_mode",
    "save_theme_mode_to_env",
    "get_upload_mode",
    "save_upload_mode_to_env",
    "THEME_AUTO",
    "THEME_DARK",
    "THEME_LIGHT",
    "UPLOAD_NEVER",
    "UPLOAD_MANUAL",
    "UPLOAD_AUTO",
    "DEFAULT_REQUESTS_PER_MINUTE",
    "DEFAULT_SCAN_WORKERS",
    "DEFAULT_UPLOAD_TIMEOUT_MINUTES",
]
